CREATE TABLE IF NOT EXISTS TEAMS (
	ID NUMERIC AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	DELETED TIMESTAMP NULL,
	CITY VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	COLORS ARRAY NULL
);